---
apiVersion: v1
kind: Service
metadata:
  name: admin_webpage
spec:
  type: LoadBalancer
  selector:
    app: admin
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin_webpage
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
      
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: webpage
        image: us-central1-docker.pkg.dev/kube-429706/demo/html:latest