name: Build PUSH to GCR

on:
  push:
    branches:
    - 'main'

jobs:
  deploy: 
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env: 
        image_name: webpage
    steps:

    - name: code checkout
      uses: actions/checkout@v4

    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}    
        #install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: Authenticate Docker to Google Container Registry
      run: gcloud auth configure-docker    
    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/my-app:${{ github.sha }} .
    - name: Push Docker image
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/kube-429706/admin/webpage:latest .
        docker push us-central1-docker.pkg.dev/kube-429706/admin/webpage:latest

   