name: Build PUSH to GCR

on:
  push:
    branches:
    - 'main'

jobs:
  deploy: 
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env: 
        image_name: webpage
    steps:

    - name: code checkout
      uses: actions/checkout@v4

    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}    
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: Authenticate Docker to Google Container Registry
      run: gcloud auth configure-docker    
    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/my-app:${{ github.sha }} .
    
    - name: Push Docker Image to GCR
      run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SA_KEY  }}/my-app:${{github.sha}}

   